name: Backend Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  backendDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "code-rush-backend"
          heroku_email: "gamersinstinct6@gmail.com"
          branch: master
          appdir: backend
        env:
          HD_DB_CONNECTION: ${{secrets.DB_CONNECTION}}
          HD_CODE_COMPILER_URL: ${{secrets.BACKEND_CODE_COMPILER}}
          HD_CODE_COMPILER_ACCESS_TOKEN: ${{secrets.BACKEND_CODE_COMPILER_ACCESS_TOKEN}}
      - run: echo "Deployed to code-rush-backend.herokuapp.com"