name: Backend Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  backendDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          DECRYPTER_PASSPHRASE: ${{secrets.DECRYPTER_PASSPHRASE}}
        run: >
          ./.github/scripts/backend_decrypt.sh
      - run: |
          cat backend/.env
          ls backend/
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "code-rush-backend"
          heroku_email: "gamersinstinct6@gmail.com"
          branch: master
          appdir: backend
          env_file: ".env"
      - run: |
          ls -a
          echo "Deployed to code-rush-backend.herokuapp.com"